name: Upload Gamemodes

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
    deploy_gamemodes:
      #if: github.event.pull_request.merged == true || github.event.workflow_dispatch.
      runs-on: ubuntu-latest
      name: deploy_gamemodes
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Update Gamemode Files
          uses: wlixcc/SFTP-Deploy-Action@v1.2.4
          with:
             username: ${{ secrets.FTP_USERNAME }}
             server: ${{ secrets.FTP_SERVER }}
             port: ${{ secrets.FTP_PORT }}
             local_path: './gamemodes/*'
             remote_path: '/garrysmod/gamemodes'
             sftp_only: true
             password: ${{ secrets.FTP_PASSWORD }}
