name: Create Test Server

on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create_server:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Download steamcmd
      run: |
            sudo apt update
            sudo apt install software-properties-common
            sudo dpkg --add-architecture i386
            sudo apt update
            echo steam steam/question select "I AGREE" | sudo debconf-set-selections
            echo steam steam/license note '' | sudo debconf-set-selections
            sudo apt install steamcmd
            echo "installed"
            pwd

    - name: Install Server
      run: |
            mkdir ./gmod
            steamcmd +force_install_dir /home/runner/work/gmodcicdtest/gmodcicdtest/gmod +login anonymous +app_update 4020 validate +quit

    - name: Start Server
      run: |
            pwd
            cd gmod
            ./srcds_run -condebug -console -game garrysmod +gamemode sandbox +map gm_construct +maxplayers 160 -tickrate 33 +exits